### ISSUE TITLE
paolobenve/myphptoshare

### ISSUE THREAD

**Issue by paolobenve** [pR0Ps/PhotoFloat#28]
Did you give a try to https://gitlab.com/paolobenve/myphotoshare ? I kept developing the original photofloat and gave it a new name.

Many many new features, and perhaps your work can be merged!

**Comment by pR0Ps** [comment]
I've taken a look at your project and I think our visions for what we want out of the project are a bit different. I've been taking some ideas and re-purposing some code from it though which has been helpful. Feel free to pull any code or ideas from this project into yours as well!
